{
 "title": "Alephium Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "broker",
    "label": "Broker:",
    "query": {
     "query": "label_values(up{app=\"alephium\",component=\"broker\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>General</span>\n</div>"
   }
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{app=\"alephium\",component=\"broker\",instance=\"$broker\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app=\"alephium\",component=\"broker\",instance=\"$broker\"}"
    }
   ]
  },
  {
   "title": "Number of Peers",
   "type": "stat",
   "description": "Number of connected peers",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alephium_peers_total{app=\"alephium\",instance=\"$broker\"}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_join(jvm_info{app=\"alephium\",instance=\"$broker\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 6 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{app=\"alephium\",component=\"broker\",instance=\"$broker\"}*1000"
    }
   ]
  },
  {
   "title": "Alephium Version",
   "type": "stat",
   "description": "Alephium Version",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alephium_build_info{app=\"alephium\",instance=\"$broker\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>Mempool</span>\n</div>"
   }
  },
  {
   "title": "Transaction Count Per Group (Shared Pool)",
   "type": "graph",
   "description": "Number of transactions in shared pool per group",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (group_index, chain_index)(alephium_mempool_shared_pool_transactions_total{app=\"alephium\",instance=\"$broker\"})",
     "legendFormat": "group {{group_index}}, chain {{chain_index}}"
    }
   ]
  },
  {
   "title": "Total Transaction Count (Shared Pool)",
   "type": "graph",
   "description": "Total number of transactions in shared pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (alephium_mempool_shared_pool_transactions_total{app=\"alephium\"}) by (instance)",
     "legendFormat": "Overall {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Count Per Group (Pending Pool)",
   "type": "graph",
   "description": "Number of transactions in pending pool per group",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (group_index,instance)(alephium_mempool_pending_pool_transactions_total{app=\"alephium\"})",
     "legendFormat": "Group index: {{group_index}} {{instance}}"
    }
   ]
  },
  {
   "title": "Total Transaction Count (Pending Pool)",
   "type": "graph",
   "description": "Total number of transactions in pending pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(alephium_mempool_pending_pool_transactions_total{app=\"alephium\"}) by (instance)",
     "legendFormat": "Overall {{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>Network</span>\n</div>"
   }
  },
  {
   "title": "Download Speed Per Peer",
   "type": "graph",
   "description": "Download Speed (byte/second) per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_download_bytes_total{app=\"alephium\",instance=\"$broker\"}[2m])) by (remote_address)",
     "legendFormat": "remote_address: {{remote_address}}"
    }
   ]
  },
  {
   "title": "Download Speed Total",
   "type": "graph",
   "description": "Total download Speed (byte/second)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_download_bytes_total{app=\"alephium\"}[2m])) by (instance)",
     "legendFormat": "Overall {{instance}}"
    }
   ]
  },
  {
   "title": "Upload Speed Per Peer",
   "type": "graph",
   "description": "Upload Speed (byte/second) per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_upload_bytes_total{app=\"alephium\",instance=\"${broker}\"}[1m])) by (remote_address)",
     "legendFormat": "{{remote_address}}"
    }
   ]
  },
  {
   "title": "Upload Speed Total",
   "type": "graph",
   "description": "Total upload Speed (byte/second)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_upload_bytes_total{app=\"alephium\"}[1m])) by (instance)",
     "legendFormat": "Overall {{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 46 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>Chain Validation</span>\n</div>"
   }
  },
  {
   "title": "Number of Payload Per Second (Per Payload)",
   "type": "graph",
   "description": "Number of payload per second, group by payload",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_payload_total{app=\"alephium\",instance=\"${broker}\"}[1m])) by (payload_type)",
     "legendFormat": "{{payload_type}}"
    }
   ]
  },
  {
   "title": "Total Number of Payload Per Second",
   "type": "graph",
   "description": "Total number of payload per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_payload_total{app=\"alephium\"}[1m])) by (instance)",
     "legendFormat": "Overall {{instance}}"
    }
   ]
  },
  {
   "title": "Total Chain Validations Per Second",
   "type": "graph",
   "description": "Chain validation per second (Block and BlockHeader)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_chain_validation_total{app=\"alephium\"}[1m])) by (validation_type,instance)",
     "legendFormat": "{{validation_type}} {{instance}}"
    }
   ]
  },
  {
   "title": "Chain Validation Time",
   "type": "graph",
   "description": "Validation time, both block validation and header validation. \n\n50 percentile, 90 percentil and 99 percentile",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(alephium_chain_validation_duration_milliseconds_bucket{app=\"alephium\",instance=\"${broker}\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(alephium_chain_validation_duration_milliseconds_bucket{app=\"alephium\",instance=\"${broker}\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(alephium_chain_validation_duration_milliseconds_bucket{app=\"alephium\",instance=\"${broker}\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Failed Validations Per Second",
   "type": "graph",
   "description": "Failed chain validation per second (Block and BlockHeader)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_chain_validation_failed{app=\"alephium\"}[1m])) by (validation_type, invalid_status, instance)",
     "legendFormat": "{{validation_type}} {{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 76 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>Blocks and Transactions</span>\n</div>"
   }
  },
  {
   "title": "Current Block Height Per Chain",
   "type": "bargauge",
   "description": "Current Block Height Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(alephium_block_current_height{app=\"alephium\",instance=\"${broker}\"}) by (chain_from, chain_to)",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Current Block Height",
   "type": "stat",
   "description": "Current Block Height",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(alephium_block_current_height{app=\"alephium\",instance=\"${broker}\"})",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Total Blocks Per Chain",
   "type": "bargauge",
   "description": "Total Blocks Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(alephium_blocks_total{app=\"alephium\",instance=\"${broker}\"}) by (chain_from, chain_to)",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Total Blocks",
   "type": "stat",
   "description": "Total Blocks Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(alephium_blocks_total{app=\"alephium\",instance=\"${broker}\"})",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Blocks Per Second Per Chain",
   "type": "graph",
   "description": "Blocks Per Second Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_blocks_received_total{app=\"alephium\",instance=\"${broker}\"}[1m])) by (chain_from, chain_to)",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Total Blocks Per Second",
   "type": "graph",
   "description": "Total Blocks Per Second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_blocks_received_total{app=\"alephium\",instance=\"${broker}\"}[1m]))",
     "legendFormat": "instant"
    },
    {
     "expr": "sum(rate(alephium_blocks_received_total{app=\"alephium\",instance=\"${broker}\"}[1h]))",
     "legendFormat": "Average 1h"
    }
   ]
  },
  {
   "title": "Transaction Per Second Per Chain",
   "type": "graph",
   "description": "Transaction Per Second Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_transactions_received_total{app=\"alephium\",instance=\"${broker}\"}[1m])) by (chain_from, chain_to)",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Total Transaction Per Second",
   "type": "graph",
   "description": "Total ransaction Per Second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_transactions_received_total{app=\"alephium\",instance=\"${broker}\"}[1m]))",
     "legendFormat": "Instant"
    },
    {
     "expr": "sum(rate(alephium_transactions_received_total{app=\"alephium\",instance=\"${broker}\"}[1h]))",
     "legendFormat": "Average 1h"
    }
   ]
  },
  {
   "title": "Block Time ",
   "type": "graph",
   "description": "Block Time with Percentil",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(alephium_block_duration_milliseconds_bucket{instance=\"${broker}\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(alephium_block_duration_milliseconds_bucket{instance=\"${broker}\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(alephium_block_duration_milliseconds_bucket[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(alephium_block_duration_milliseconds_sum[1m]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Total Headers Per Chain",
   "type": "bargauge",
   "description": "Total Headers Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "alephium_headers_total{app=\"alephium\",instance=\"${broker}\"}",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Total Headers",
   "type": "stat",
   "description": "Total Headers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(alephium_headers_total{app=\"alephium\",instance=\"${broker}\"})",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Headers Per Second Per Chain",
   "type": "graph",
   "description": "Headers Per Second Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_headers_received_total{app=\"alephium\",instance=\"${broker}\"}[1m])) by (chain_from, chain_to)",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Total Headers Per Second",
   "type": "graph",
   "description": "Total Headers Per Second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alephium_headers_received_total{app=\"alephium\",instance=\"${broker}\"}[1m]))",
     "legendFormat": "Overall"
    }
   ]
  }
 ]
}